package model2;
// Generated 07/06/2020 20:37:23 by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade implements java.io.Serializable {

	private long id;
	private Estado estado;
	private String nome;
	private Integer ibge;
	private Set hemocentros = new HashSet(0);

	public Cidade() {
	}

	public Cidade(long id) {
		this.id = id;
	}

	public Cidade(long id, Estado estado, String nome, Integer ibge, Set hemocentros) {
		this.id = id;
		this.estado = estado;
		this.nome = nome;
		this.ibge = ibge;
		this.hemocentros = hemocentros;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Integer getIbge() {
		return this.ibge;
	}

	public void setIbge(Integer ibge) {
		this.ibge = ibge;
	}

	public Set getHemocentros() {
		return this.hemocentros;
	}

	public void setHemocentros(Set hemocentros) {
		this.hemocentros = hemocentros;
	}

}
