package model2;
// Generated 07/06/2020 20:37:23 by Hibernate Tools 5.4.3.Final

/**
 * Hemocentro generated by hbm2java
 */
public class Hemocentro implements java.io.Serializable {

	private long id;
	private Cidade cidade;
	private Estado estado;
	private String nome;
	private String endereco;
	private Integer cep;
	private String telefone;
	private String email;
	//private byte[] estado_1;

	public Hemocentro() {
	}

	public Hemocentro(long id) {
		this.id = id;
	}

	public Hemocentro(long id, Cidade cidade, Estado estado, String nome, String endereco, Integer cep, String telefone, String email,
			byte[] estado_1) {
		this.id = id;
		this.cidade = cidade;
		this.estado = estado;
		this.nome = nome;
		this.endereco = endereco;
		this.cep = cep;
		this.telefone = telefone;
		this.email = email;
		//this.estado_1 = estado_1;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public Integer getCep() {
		return this.cep;
	}

	public void setCep(Integer cep) {
		this.cep = cep;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	/*public byte[] getEstado_1() {
		return this.estado_1;
	}

	public void setEstado_1(byte[] estado_1) {
		this.estado_1 = estado_1;
	}
*/
}
