package model;
// Generated 07/06/2020 17:49:58 by Hibernate Tools 5.4.3.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;

/**
 * Hemocentro generated by hbm2java
 */
@Entity
@NamedQuery(name = "Hemocentro.findAll", query = "SELECT h FROM Hemocentro h")
public class Hemocentro implements java.io.Serializable {

	private static final long serialVersionUID = -340911560648258215L;
	@Id
	private long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cidade")
	private Cidade cidade;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado")
	private Estado estado;

	private String nome;
	private String endereco;
	private Integer cep;
	private String telefone;
	private String email;

	public Hemocentro() {
	}

	public Hemocentro(long id) {
		this.id = id;
	}

	public Hemocentro(long id, Cidade cidade, Estado estado, String nome, String endereco, Integer cep, String telefone, String email) {
		this.id = id;
		this.cidade = cidade;
		this.estado = estado;
		this.nome = nome;
		this.endereco = endereco;
		this.cep = cep;
		this.telefone = telefone;
		this.email = email;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public Integer getCep() {
		return this.cep;
	}

	public void setCep(Integer cep) {
		this.cep = cep;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
